console.log(Math.E);
console.log(Math.PI);
console.log(Math.round(1.6));
console.log(Math.ceil(1.6));
console.log(Math.floor(1.6));
console.log(Math.trunc(1.6));
console.log(Math.pow(2, 3));
console.log(Math.sqrt(2));
console.log(Math.abs(2));
console.log(Math.min(1, 2, 3, 4, 5));
console.log(Math.max(1, 2, 3, 4, 5));
console.log(Math.random());
